### ISSUE TITLE
Hva ser brukeren når de ikke finner gravferdsbyrået de søker etter?

### ISSUE THREAD

**Issue by AstridDigdir** [Altinn/digital-gravferd#112]
Ref #103 

Hvis brukeren ikke finner gravferdsbyrået sitt så skal de få en oppfordring om å gå til gravferdsbyrået direkte. De vil ikke få anledning til å fullføre innsendingen av skjemaet.

**Comment by AstridDigdir** [comment]
Påbegynt: [Figmaskisse](https://www.figma.com/file/f3FeSdA0yWgFlJq4AoTNTl/Konseptskisser?type=design&node-id=6110-49789&mode=design&t=MnllzhBNFcAB27QT-4)

**Comment by AstridDigdir** [comment]
Setter til gjennomgang av Merete og Ola.

**Comment by OlaDGM** [comment]
Jeg forutsetter at dette gjelder MVP-Pilot og gir tommel opp @AstridDigdir
