### ISSUE TITLE
Valg av krematorium på kommunenivå

### ISSUE THREAD

**Issue by moffan** [Altinn/digital-gravferd#117]
### Description

Vi setter krematorium ut i fra datasett basert på siste års statistikk pr kommune. Vi tar utgangspunkt i at det er  bostedskommunen som avgjør hvor du skal kremeres. Krematoriet som var mest brukt i fjoråret skal velges.

### Additional Information

Erik utarbeider listen over brukte krematorier basert på statistikken.
Vi trenger å utrede om det er bostedskommunen som er korrekt her, dette må gjøres i et møte med GFB og GPM.

### Tasks

- [ ] #116

**Comment by moffan** [comment]
Etter team møte er det konkludert med at vi setter krematorium basert på bodstedskommunen, og hvis det av en eller annen grunn skal byttes krematorium er det GFB som representerer GFA som har mulighet å endre dette i løsningen for MVP

**Comment by OlaDGM** [comment]
Da må vel denne få en decisions label?
