### ISSUE TITLE
New endpoint: POST: /sfvt/dgm-gravferden/api/funerals/lookup

### ISSUE THREAD

**Issue by chrrust** [Altinn/digital-gravferd#119]
### Description

The purpose of this endpoint is to provide the means to lookup the funerals that a person is eligible to take responsibility of.

The request body will contain the social security number (SSN) of the stakeholder/next-of-kin of the funeral.
The response will contain a list of funerals.

**Details**
Method: POST
Path: {org}/{app}/api/funerals/lookup

**Comment by mikaelrss** [comment]
Works as expected 🎉
