### ISSUE TITLE
New endpoint: POST /api/funeralhome/funerals/attach-stakeholder

### ISSUE THREAD

**Issue by chrrust** [Altinn/digital-gravferd#120]
### Description

Purpose of endpoint: Attach a new stakeholder to a funeral. This is a prerequisite to submit a statement of responsibility for people who are not direct relations to the deceased in Folkeregisteret.

Method: POST
RequestBody:
```json
{
  "stakeholderSsn": "31127012345",
  "deceasedSsn": "17095054321",
  "relationToDeceasedPerson": "samboer"
}
```

**Comment by mikaelrss** [comment]
Getting a 404 when I'm trying to test this endpoint against sfvt-env

**Comment by mikaelrss** [comment]
Tested now, and works as expected! Nice job! 😄
