### ISSUE TITLE
Skrive kun "Statsforvalteren" i stedet for "Statsforvalteren i Vestfold og Telemark" i hele/begge appene

### ISSUE THREAD

**Issue by AstridDigdir** [Altinn/digital-gravferd#130]
Trenger ny logo fra @erikhynne ?

**Comment by mikaelrss** [comment]
Har fått ny logo fra @erikhynne og implementert for ansvarlig appen.

**Comment by mikaelrss** [comment]
Denne er ferdig nå og kan testes for begge appene @AstridDigdir

**Comment by AstridDigdir** [comment]
Alt-texten på logoen er fortsatt "Statsforvalteren i Vestfold og Telemark" :)
Og hvordan kan jeg teste den andre appen?

**Comment by mikaelrss** [comment]
@AstridDigdir Du kan teste bytte-appen på [denne lenken](https://sfvt.apps.tt02.altinn.no/sfvt/dgm-bytte-ansvarlig) Du kan logge inn med de samme brukerene som på ansvarlig-appen

**Comment by AstridDigdir** [comment]
Takk! Sett gjennom, og ser at alt-teksten og den synlige teksten ser bra ut i begge appene 👍
