### ISSUE TITLE
Update relation to the deceased with common language

### ISSUE THREAD

**Issue by mikaelrss** [Altinn/digital-gravferd#54]
### Description of the bug

As of right now, the current roles that are displayed are `"... din (mor|far|barn|ektefelleEllerPartner)`, resulting in alerts that look like this: 

![image](https://github.com/Altinn/digital-gravferd/assets/26043795/24bef58d-6df8-46b4-bed4-a1ebea860164)
![image](https://github.com/Altinn/digital-gravferd/assets/26043795/2aca487b-b43d-40e5-8646-4781604a0713)

The message should display `"... er din ektefelle eller parter"` or `"... er ditt barn"`

### Steps To Reproduce

1. Go to ansvarlig
2. Login with Pengelens Partner
3. Start the form and observe the erroneous alerts stating the deceased's relation.

**Comment by moffan** [comment]
testet ok på tt02, med alle personnummer
![Image](https://github.com/Altinn/digital-gravferd/assets/938091/a217a31e-fa89-42fa-a53a-9a4bc158d9a2)
