### ISSUE TITLE
Create burial instance when some is registered as dead in FReg

### ISSUE THREAD

**Issue by moffan** [Altinn/digital-gravferd#6]
### Description

Create an instance of the "burial app" on the deceased when we receive an event from the "dgm-events" that someone is dead. 

### Additional Information

- [Subscribe to events](https://docs.altinn.studio/events/subscribe-to-events/)

### Acceptance Criterias

We have a instance of "gravferden" for the deceased when receiving the event that someone is dead (from dgm-events)

**Comment by thechrrust** [comment]
Implemented in Gitea
- https://altinn.studio/repos/ttd/dgm-gravferden/pulls/5
- https://altinn.studio/repos/ttd/dgm-gravferden/pulls/6
- https://altinn.studio/repos/ttd/dgm-gravferden/pulls/7
- https://altinn.studio/repos/ttd/dgm-gravferden/pulls/8

New issues have been spawned to handle what has not been implemented for now:
- https://github.com/Altinn/digital-gravferd/issues/34
- https://github.com/Altinn/digital-gravferd/issues/39
- https://github.com/Altinn/digital-gravferd/issues/36
