### ISSUE TITLE
Add logo of Statsforvalteren to the app

### ISSUE THREAD

**Issue by mikaelrss** [Altinn/digital-gravferd#67]
### Description

Add the logo of Statsforvalteren i Vestfold og Telemark to `dgm-ansvarlig`.

### Additional Information

Related issues:
- https://github.com/Altinn/app-frontend-react/issues/138

### Acceptance Criterias

- [x] The logo of "Statsforvalteren i Vestfold og Telemark" is visible at the top of the form
- [x] Altinn's logo is visible in the footer of the form
- [x] Both alt-texts are correct and describes the image according to WCAG 2.1

**Comment by AstridDigdir** [comment]
Looks good, except that the alt-text is "Testdepartementet". But this is set with the name of the service owner and should be correct at launch.
