### ISSUE TITLE
Add PDF Summary

### ISSUE THREAD

**Issue by mikaelrss** [Altinn/digital-gravferd#68]
### Description

As a user, I want to be able to see a PDF summary of the data I'm about to submit

**Comment by mikaelrss** [comment]
- Dette er fordi vi ikke har lagt inn noe adresse til en lenke tipper jeg. Lenken fungerer ikke på forsiden heller. Har du en URL som vi skal putte inn der? 
- hm, hva mener du med at svaret er en "Content list"? Noe som blir lest opp av Voice Over? Det skjer ikke på `orca` i hvert fall
- Ser ikke ut til at vi har muligheten til å kontrollere header-nivået. Vi kan alltids vurdere å droppe `Panel`-komponenten på denne siden da.

**Comment by AstridDigdir** [comment]
- Ok, gir mening. Nei, ikke ennå.
- Har sett tagstrukturen i Acrobat Reader nå, og uten å ha veldig mye erfaring med det så ser det ikke ut som at det er noe feil. Den skiller seg i hvert fall ikke ut fra resten av innholdet. 
- Ja, den siden er jo litt under arbeid uansett, så vi kan la det ligge for nå. Uansett ikke veldig farlig.
