### ISSUE TITLE
Pilot area funeral agency list

### ISSUE THREAD

**Issue by mikaelrss** [Altinn/digital-gravferd#85]
### Description

For the pilot, the funeral agency search should be populated with data about funeral agencies from the pilot area

**Comment by chrrust** [comment]
Is the list supposed to be empty when nothing is searched for?

![Image](https://github.com/Altinn/digital-gravferd/assets/4062582/c1609a6b-edbc-46cc-acb9-c8bd6b27fb17)

**Comment by mikaelrss** [comment]
Yes, I think so. @AstridDigdir?

**Comment by AstridDigdir** [comment]
The best solution would be that the list isn't shown at all before there's anything in it.

**Comment by mikaelrss** [comment]
Aha. I'm not sure if that is possible. Will check.

**Comment by AstridDigdir** [comment]
If it's not possible, can we have an epmty state, with an epmty row just stating something like "Søkeresultater vil vises her"

**Comment by mikaelrss** [comment]
Agreed with @AstridDigdir that the search field also should be hidden and we should show an alert if the user inputs a search that has no search results. [Sketches](https://www.figma.com/file/f3FeSdA0yWgFlJq4AoTNTl/Konseptskisser?type=design&node-id=6110-49814&mode=design&t=E2fmMeXwmI7Kxwa5-4)

**Comment by chrrust** [comment]
Let me know when this is ready for test again 😃

**Comment by mikaelrss** [comment]
![Image](https://github.com/Altinn/digital-gravferd/assets/26043795/60645061-2bcc-4d18-bab4-d3fe555d377e)

I think the solution we agreed upon might not be ideal @chrrust

**Comment by mikaelrss** [comment]
@AstridDigdir I guess this behavior might not be what we want. Do we need to think of alternatives?

**Comment by AstridDigdir** [comment]
Definitely not. Let me know when you know more about whether or not it can be solved. I would really like an alert of some kind to tell the user that if they cannot find the funeral director they're looking for, then they can't use this service.

**Comment by mikaelrss** [comment]
@AstridDigdir @chrrust I tried a different approach. There is still some delay between the search results actually being empty and when the field disappears, but I think this solution is better than the previous. The alert will not show up before we actually know that there is a failed search.

![Image](https://github.com/Altinn/digital-gravferd/assets/26043795/7f1c6a4d-604b-48b9-8904-297cd7ae565a)

**Comment by AstridDigdir** [comment]
Sånn som det er nå så kan man få opp alerten før man er ferdig med å skrive, noe jeg synes er ganske irriterende. Er det en idé å sette en begrensning slik at den ikke setter i gang å søke før man har skrevet f.eks. minst tre karakterer? 
Eksempel på slik den er nå: 
- "H" > "Ingen treff"
- "Ho" > "Ingen treff"
- "Hor" > "Horten begravelsesbyrå"

Søket er forøvrig litt uforutsigbart. Søker jeg på "O" får jeg opp "Holmestrand" og "Høybråten", mens hvis jeg søker på "Os" eller "Ose" får jeg ingen treff, og hvis jeg søker på "Oseb" får jeg opp "Oseberg begravelsesbyrå". Men kanskje det blir bedre med et minstekrav om 3-4 karakterer.

**Comment by AstridDigdir** [comment]
Pluss! Kan vi legge inn en liten forklarende tekst under label-en med "Søk etter nav eller sted", slik som i prototypen? :)

**Comment by mikaelrss** [comment]
> Pluss! Kan vi legge inn en liten forklarende tekst under label-en med "Søk etter navn eller sted", slik som i prototypen? :)

Det tror jeg ikke vi får til uten å brekke UU. Da må det legges til som to separate tekster, og da blir ikke "Hvilket graveferdsbyrå skal du bruke?" en del av labelen til input-feltet.

**Comment by mikaelrss** [comment]
> Søket er forøvrig litt uforutsigbart. Søker jeg på "O" får jeg opp "Holmestrand" og "Høybråten", mens hvis jeg søker på "Os" eller "Ose" får jeg ingen treff, og hvis jeg søker på "Oseb" får jeg opp "Oseberg begravelsesbyrå". Men kanskje det blir bedre med et minstekrav om 3-4 karakterer.

Du treffer "Høybråten Blomster og Begravelsesbyrå AS" og "Holmestrand Begravelsesbyrå, Aas og Tuftes Eftf." fordi begge disse inneholder ordet "og" som treffer godt på søketermen "o". 

Vi kan nok legge til en liste med ord vi vil utelate fra søket, som for eksempel "og", "med", "til", "i"  osv.

**Comment by mikaelrss** [comment]
> Sånn som det er nå så kan man få opp alerten før man er ferdig med å skrive, noe jeg synes er ganske irriterende. Er det en idé å sette en begrensning slik at den ikke setter i gang å søke før man har skrevet f.eks. minst tre karakterer?
Eksempel på slik den er nå:

Vi kan se om vi får til søket med minimumsbegrensing på karakterer i søketermen. Kanskje vi kan gjøre det etter brukertestene?

**Comment by mikaelrss** [comment]
Vi gjør ingenting mer med denne før vi har gjennomført brukertester
