### ISSUE TITLE
Option for not selecting municipality of death

### ISSUE THREAD

**Issue by mikaelrss** [Altinn/digital-gravferd#88]
### Description

The person responsible for the funeral might not always know where the deceased person died. Therefore users should be able to move on to the next page without specifying this. 

### Additional Information

En checkbox med "Vet ikke" alternativ, som disabler comboboxen når den er krysset av. Rent strukturelt må da disse to skjemaobjektene grupperes slik at de i koden er begge skjemaobjekter relatert til spørsmålet. F.eks <fieldset> rundt objektene i koden, som peker til en <legend> som er tittelen til gruppen.

[Skisser](https://www.figma.com/file/f3FeSdA0yWgFlJq4AoTNTl/Konseptskisser?type=design&node-id=1384-65740&mode=design&t=CaUVWLuPfloNYBTW-4)

**Comment by chrrust** [comment]
Looks good to me. I created a new issue to handle the conditional logic of the municipality of death in dgm-gravferden: #100
