### ISSUE TITLE
URL for "les mer" in intro page

### ISSUE THREAD

**Issue by mikaelrss** [Altinn/digital-gravferd#94]
### Description

We need a link to a page with even more information for the intro page.

**Comment by mikaelrss** [comment]
@AstridDigdir You were saying that this URL already was determined? Could you post it here? 🙏

**Comment by AstridDigdir** [comment]
prosjekt.statsforvalteren.no/gravferd

**Comment by AstridDigdir** [comment]
Jeg ser at lenken er riktig 👌🏻
