### ISSUE TITLE
Move retrieval of funeral agencies from dgm-ansvarlig to dgm-gravferden

### ISSUE THREAD

**Issue by chrrust** [Altinn/digital-gravferd#99]
### Description

The current use of the funeral agencies list is in `dgm-ansvarlig`. There it is used to provide a search for funeral agency for the user.

A new need has emerged where we will need to lookup a funeral agency based on its organization number. To avoid duplication of the funeral agency dataset, we have decided to move it into `dgm-gravferden` and to adda new endpoint for retrieving the list of funeral agencies

In the future this might be moved again into its own micro service, but until then it will reside inside `dgm-gravferden`

### Additional Information

- Location of the list - [link](https://altinn.studio/repos/ttd/dgm-ansvarlig/src/branch/master/App/data)

### Acceptance Criterias

- `dgm-ansvarlig` should now retrieve the list of funeral agencies from `dgm-gravferden`
- new endpoint for retrieving all funeral agencies

**Comment by chrrust** [comment]
Discussed with @mikaelrss that we will move the fuzzy query logic into dgm-gravferden aswell so we can do string query on the funeral homes on the endpoint in dgm-gravferden. We decided we should cache the search query string and that we should in the beginning add a stopwatch to monitor the time it takes to do the query to better evaluate the implications of the solution in dgm-ansvarlig

**Comment by mikaelrss** [comment]
The search works as expected 🙌 Good job!
